

GET http://localhost:5005/users







###






DELETE http://localhost:5005/users/5f383023b2e03546174f1544







###








POST http://localhost:5005/users
Content-Type: application/json

{
    "username": "Tjcharm",
    "password": "Test password",
    "email": "test email"
    
    }







###









GET http://localhost:5005/users/5f38307d2188eb464597ee43







###





PATCH  http://localhost:5005/users/5f38307d2188eb464597ee43
Content-Type: application/json

{
   "email": "test email 2"
}



